### ISSUE TITLE
AttributeError: 'GenerationModel' object has no attribute 'mask_pix'

### ISSUE THREAD

**Issue by tyc97-sys** [wanghu178/KUNet#1]
I change network_G which_model_G of `train_KIB.yml` to `KIB_DM_F_1x1_mask`, but got this error:
```
22-06-30 11:35:58.139 - INFO: Model [GenerationModel] is created.
22-06-30 11:35:58.139 - INFO: Start training from epoch: 0, iter: 0
Traceback (most recent call last):
  File "F:/code/KUNet-main/codes/train.py", line 171, in <module>
    model.optimize_parameters(current_step)
  File "F:\code\KUNet-main\codes\models\Generation_condition.py", line 111, in optimize_parameters
    KIB1_loss = self.mask_pix(KIB1,self.real_H,mask)
AttributeError: 'GenerationModel' object has no attribute 'mask_pix'
```
How can I fix it, thanks!

**Comment by wanghu178** [comment]
Thank you very much for your interest in our work！ For this question: Please change the loss function to “maskl1_l1“ when adding the mask.   I will explain the configuration in detail in a future release
